@echo off
echo Compiling Java files...
javac -d out -cp src src\Common\*.java src\Node\*.java src\Coordinator\*.java src\Clients\*.java src\Main.java

echo Starting CoordinatorServer on port 5000...
start cmd /k java -cp out Coordinator.CoordinatorServer

echo Starting Node1 on port 6001...
start cmd /k java -cp out Node.Node1Server

echo Starting Node2 on port 6002...
start cmd /k java -cp out Node.Node2Server

echo Starting Node3 on port 6003...
start cmd /k java -cp out Node.Node3Server

echo Starting EmployeeClient...
start cmd /k java -cp out Clients.EmployeeClient

echo Starting ManagerClient...
start cmd /k java -cp out Clients.ManagerClient
